### ISSUE TITLE
Multiple selection states switched back after event handler MF execution completed   

### ISSUE THREAD

**Issue by odi76** [bsgriggs/mendix9-searchable-reference-selector#9]
When you quickly make multiple option-changes (set on/off an option) and the on-change event handler MF needs plenty of time (1-2 sec) to be completed, then the state of selected options goes back to the state after you made the first selection change.
For example, options A is already selected and you select B, C, D, and E in a row. The MF started executing immediately after you selected B but has not finished during you have selected C, D, and E. It seems all fine to 1-2 sec, but after the MF execution completed, then the selected options C, D, and E is switched off again.

**Comment by odi76** [comment]
I would say that revising the event triggering could help. That is, the on-change event would be generated only after making all changes and switching the focus from the widget can precede the situation.

**Comment by bsgriggs** [comment]
Hi Istvan,
My idea to address this problem is to add a setting called showLoadingAnimation. When enabled, it will ignore any selection the user makes while the on-change action or the data source is running. During this time it will show an animated loading icon similar to React-Select (see sample video below).

I'll make this setting false by default because it can be quite annoying for the icon to flicker in and out of existence when the on-change action/data source is very quick.

What are your thoughts on this approach? Do you have any other ideas to address this UX issue or ideas for improving my approach?

(on-change action has a delay of 2000 ms)

https://user-images.githubusercontent.com/47681665/208150672-c7111f98-de22-4994-951f-258a04101c9c.mp4

**Comment by odi76** [comment]
Of course, I gladly shared my thoughts, but I could not keep it shortly - sorry.

I would make a distinction between the single and multiple selection. Your video focuses only on the first case, but I have to face to the another situation. so I am still interested in how that opearion should be imagined by this soltuion.
I feel this difference in the flow of interaction. When you need to select only single item, then the flow ends with having selected the item, but in the other case the flow should not either be blocked until all changes have been made and the user "finishes thier job". So if you would play a short animation after each change, then it could bother the UX quite a lot, as you also mentioned ("it can be quite annoying").

In addition, I would say the multiselection scenario looks like the usage scenario of editbox. So during editing a text in an editbox, you do not finish the modification by adding/removing each single character. but only by a specific action (e.g. pushing Enter, Tab or other UI element) which can unmistakably reflect this event to trigger the correspondance action handler.

Finally, another scenario/context to be considered. I use this widget as a filtering field for datagrids. I apply plenty of them, and some of them have even some interdependencies as well. For instance, a filter 'location' values depend on the filter 'company' values. If you have selected specific companies, the set of available locations and the currently selected items are constrained by the selected companys' locations. (Company has one or more assigned locations.) Why is this interesting? Because the selected location options shall be maintained in accord with the selected companies. I have to deselect a location if its company is not selected anymore. And this maintenance should not make during the flow described above. It should be done only after the flow ends, because the user can deselect a country accidentally and such an action could deselect the correspondent location if each selection events trigger the on-change event. Even if the user reselect the company again, the removed location(s) cannot be restored since they are not known any more.

So I would not apply such a delay at multiple selection scenario, but provide an event triggered by the end of the flow on which a MF can subscribe. Hope I can explain/summarize my arguments quite well.

**Comment by bsgriggs** [comment]
I'm going to remove the logic that prevented on-change from overlapping and the remove animation. This way the on-change action will execute after every selection regardless if there is already an on-change running. This would fix your scenario provided you have the on-change action refresh the results of the dependent selector.

I had considered adding an "on-leave" action that would only run when the selector loses focus, but that creates an awkward scenario. If the user is expecting an action to occur after they make their final selection, they would have to click or tab away to close the menu and run the action (which isn't very intuitive). 

Food for thought: 
Generally, when the user has multi-selection, it is better performance to have a "Search" button to update the grid results instead of on-change. This is because the on-change action will execute after every selection when the user only cares about the result from all the selections. 

For example, a user wants to search for t-shirts that are either blue, red, or green. If we use an on-change action to refresh the result list, then the refresh will occur when the user clicks blue, again when they click red, and again when they click green. Since the user never cared about the results that were only blue or the results that were red or blue, the queries that ran after the first and second selections were wasted computation. Therefore, we can reduce the traffic to the server and improve performance by having the user make all of their selections and then click a "Search" button to refresh the results of the grid. 

With your use case, that would look rather complicated and may not be worth the changes. You would need a way of exclusively refreshing the data source on the dependent selector without refreshing anything else.

**Comment by odi76** [comment]
Thank you for considering the scenario.

Actually, the scenario you described with t-shirts depicts the same situation and reason why I cannot apply your current change event solution.

I have already considered the additional button as a trigger to execute the query/filtering. Actually, I had done and decided before I applied your widget. Just think about the text box! It has a similar opeartion scenario: though you edit by character, but you are interested in the completed editing. So the referred operation logic (ie. refreshing query result without pushing button) is already experienced with textbox: you also have to change the focus or just push enter in order to "finalize" the edited value. And I wouldn't say awkward. (But yes, a dedicated UI element in the widget would definitely enhance the UX with finalizing the change. This is also true for editbox and it can be useful to cancel the change.)

Well, I am sad a bit. I believed that implementing an additional event trigger for losing focus could be easy. I might be wrong.

Thanks for your enthusiasm. ...and I wish a happy new year! :-)

**Comment by bsgriggs** [comment]
change available in the latest version in the Mendix marketplace v2.0.1
